### ISSUE TITLE
Failing Edge Cases with Non-deterministic Test Results

### ISSUE THREAD

**Issue by cschanaj** [cschanaj/xhttpse2#6]
**Non-deterministic Test Results** 

`HTTPSE_SECURE_FALLBACK`

|   URL(s)    | Type| Reference| Status|
|:--------|:-----:|:------------:|:--------:|
|https://www.sfc.hk |  | https://github.com/EFForg/https-everywhere/pull/8972 ||
|https://price.com.hk |  | https://github.com/EFForg/https-everywhere/pull/8982 ||
|https://www.pixiv.net |  |  ||
|https://archive.am730.com.hk | P | https://github.com/EFForg/https-everywhere/pull/8741#pullrequestreview-26927573 | Pending Fix |
|https://m.price.com.hk | N | https://github.com/EFForg/https-everywhere/pull/8982#pullrequestreview-29689654 | Pending Fix |
|https://checkout.unicef.org.uk | N | https://github.com/EFForg/https-everywhere/pull/9491 | Pending Fix |
|https://golfdigest.com | N | https://github.com/EFForg/https-everywhere/pull/9532 | Pending Fix |

`HTTPSE_DIFFERENT_CONTENT`

|   URL(s)    | Type| Reference| Status|
|:--------|:-----:|:------------:|:--------:|
| https://slack.sumome.com ||||
| https://www.ttk-chita.ru ||||
| https://secure.worldwildlife.org | P | https://github.com/EFForg/https-everywhere/pull/9560 | Pending Fix | 
| https://habets.pp.se | P | Pending | Pending Fix | 
| https://flipbook.am730.com.hk | N | https://github.com/EFForg/https-everywhere/pull/8741#pullrequestreview-26927902 | Fixed https://github.com/cschanaj/xhttpse2/commit/589fcfa056c00c5ae5adad8298b5220e34a6de8b | 
| https://support.unian.ua | N || Fixed https://github.com/cschanaj/xhttpse2/commit/98eeb2bef251116ef46e7676dcdde68d7b5edcad |

**TODO** Missing false positive examples.

`HTTPSE_OK`

> **Important** There are in fact hosts which pass all the tests and exited with `HTTPSE_OK` but being problematic. They are likely having false-negative results from the above tests, mostly `HTTPSE_DIFFERENT_CONTENT`.

**Deterministic Test Results** 

`HTTPSE_SSL_INCOMPLETE_CERT_CHAIN`, See https://github.com/EFForg/https-everywhere/pull/8964#discussion_r106062635

- http://mnhn.fr

- http://build.webmproject.org

- http://platform.bittorrent.com

`HTTPSE_MIXED_CONTENT`

- https://club.japantimes.co.jp

- https://www.bittorrent.com

- https://test.thenewslens.com

- https://www.post852.com

- https://www.hkgolden.com

**Comment by Foorack** [comment]
Nice program you've got here. :+1:

"Edge Cases"
If you want training data, try running your program against europa.eu. I have never in my life seen as many weird edge-cases. :stuck_out_tongue:

**Comment by cschanaj** [comment]
thank you for your suggestion! I will try to run my program on `europa.eu` and look for weird edge-cases. :laughing:
